import { oklchToRgb, type Rgb } from "./color.js";
import { colors, pairs, radius } from "./tokens.js";

/**
 * The tokens, shaped for Figma.
 *
 * Figma holds channels, not perceptual coordinates, so every colour is converted
 * here rather than in the script that writes them — which keeps the arithmetic
 * testable without a Figma file, and keeps the script to the part that genuinely
 * needs the Plugin API.
 *
 * One mode. This palette is dark and has no light variant, and inventing one to
 * make the Figma collection look complete would put a lie in the design system.
 */
export const COLLECTION = "Tokens";
export const MODE = "Dark";

export type FigmaColorVariable = {
  /** `/` groups variables in Figma's UI, so `color/background` nests. */
  readonly name: string;
  readonly token: string;
  readonly value: Rgb;
  /** The surface this one is a foreground for, when it is one. */
  readonly foregroundOf?: string;
};

export type FigmaVariables = {
  readonly collection: string;
  readonly mode: string;
  readonly colors: ReadonlyArray<FigmaColorVariable>;
  readonly numbers: ReadonlyArray<{ readonly name: string; readonly value: number; }>;
};

/** `0.375rem` at a 16px root, which is what Figma measures in. */
const remToPx = (value: string): number => Number(value.replace(/rem$/, "")) * 16;

const surfaceOf = new Map(
  pairs.map(([surface, foreground]) => [foreground as string, surface as string]),
);

export const figmaVariables = (): FigmaVariables => ({
  collection: COLLECTION,
  mode: MODE,
  colors: Object.entries(colors).map(([token, value]) => {
    const surface = surfaceOf.get(token);

    return {
      name: `color/${token}`,
      token,
      value: oklchToRgb(value),
      ...(surface === undefined ? {} : { foregroundOf: surface }),
    };
  }),
  numbers: [{ name: "radius/base", value: remToPx(radius) }],
});

const round = (channel: number) => Number(channel.toFixed(4));

/**
 * The Plugin API script that writes those variables into a file.
 *
 * Generated rather than hand-written so the values cannot drift from
 * `tokens.ts`, and idempotent so running it twice updates rather than
 * duplicates — a design system is synced repeatedly, not created once.
 *
 * The Figma MCP server's own `figma-use` skill is the authority on API spelling
 * and must be loaded before this is executed; where the two disagree, the skill
 * is right and this is stale.
 */
export const figmaVariableScript = (): string => {
  const data = figmaVariables();

  const colorLines = data.colors.map((variable) =>
    `  ${JSON.stringify(variable.name)}: { r: ${round(variable.value.r)}, g: ${
      round(variable.value.g)
    }, b: ${round(variable.value.b)} },`
  ).join("\n");

  const numberLines = data.numbers.map((variable) =>
    `  ${JSON.stringify(variable.name)}: ${variable.value},`
  ).join("\n");

  return `// Generated by @vantion/tokens. Do not edit — change packages/tokens/src/tokens.ts
// and run \`bun run --filter @vantion/tokens figma:script\`.

const COLORS = {
${colorLines}
};

const NUMBERS = {
${numberLines}
};

const existing = await figma.variables.getLocalVariableCollectionsAsync();
let collection = existing.find((c) => c.name === ${JSON.stringify(data.collection)});
if (collection === undefined) {
  collection = figma.variables.createVariableCollection(${JSON.stringify(data.collection)});
}

collection.renameMode(collection.modes[0].modeId, ${JSON.stringify(data.mode)});
const modeId = collection.modes[0].modeId;

const variables = await figma.variables.getLocalVariablesAsync();
const byName = new Map(variables.map((v) => [v.name, v]));

const upsert = (name, type, value) => {
  const variable = byName.get(name) ?? figma.variables.createVariable(name, collection, type);
  variable.setValueForMode(modeId, value);
  return variable;
};

for (const [name, value] of Object.entries(COLORS)) upsert(name, "COLOR", value);
for (const [name, value] of Object.entries(NUMBERS)) upsert(name, "FLOAT", value);

figma.notify(\`Synced \${Object.keys(COLORS).length} colours and \${Object.keys(NUMBERS).length} numbers\`);
`;
};
