/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedAssistantRouteImport } from './routes/_protected/assistant'
import { Route as ProtectedContactsRouteImport } from './routes/_protected/contacts'
import { Route as ProtectedFilesRouteImport } from './routes/_protected/files'
import { Route as ProtectedSettingsRouteRouteImport } from './routes/_protected/settings/route'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthMagicLinkRouteImport } from './routes/auth/magic-link'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthVerifiedRouteImport } from './routes/auth/verified'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedSettingsApiKeysRouteImport } from './routes/_protected/settings/api-keys'
import { Route as ProtectedSettingsAuditRouteImport } from './routes/_protected/settings/audit'
import { Route as ProtectedSettingsBillingRouteImport } from './routes/_protected/settings/billing'
import { Route as ProtectedSettingsGeneralRouteImport } from './routes/_protected/settings/general'
import { Route as ProtectedSettingsMembersRouteImport } from './routes/_protected/settings/members'
import { Route as ProtectedSettingsRolesRouteImport } from './routes/_protected/settings/roles'
import { Route as AuthAcceptInvitationInvitationIdRouteImport } from './routes/auth/accept-invitation/$invitationId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAssistantRoute = ProtectedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedContactsRoute = ProtectedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFilesRoute = ProtectedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRouteRoute = ProtectedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMagicLinkRoute = AuthMagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifiedRoute = AuthVerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedSettingsRouteRoute,
} as any)
const ProtectedSettingsApiKeysRoute =
  ProtectedSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsAuditRoute = ProtectedSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ProtectedSettingsRouteRoute,
} as any)
const ProtectedSettingsBillingRoute =
  ProtectedSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsGeneralRoute =
  ProtectedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsMembersRoute =
  ProtectedSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsRolesRoute = ProtectedSettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => ProtectedSettingsRouteRoute,
} as any)
const AuthAcceptInvitationInvitationIdRoute =
  AuthAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/assistant': typeof ProtectedAssistantRoute
  '/contacts': typeof ProtectedContactsRoute
  '/files': typeof ProtectedFilesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/settings/api-keys': typeof ProtectedSettingsApiKeysRoute
  '/settings/audit': typeof ProtectedSettingsAuditRoute
  '/settings/billing': typeof ProtectedSettingsBillingRoute
  '/settings/general': typeof ProtectedSettingsGeneralRoute
  '/settings/members': typeof ProtectedSettingsMembersRoute
  '/settings/roles': typeof ProtectedSettingsRolesRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/assistant': typeof ProtectedAssistantRoute
  '/contacts': typeof ProtectedContactsRoute
  '/files': typeof ProtectedFilesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/': typeof ProtectedIndexRoute
  '/settings/api-keys': typeof ProtectedSettingsApiKeysRoute
  '/settings/audit': typeof ProtectedSettingsAuditRoute
  '/settings/billing': typeof ProtectedSettingsBillingRoute
  '/settings/general': typeof ProtectedSettingsGeneralRoute
  '/settings/members': typeof ProtectedSettingsMembersRoute
  '/settings/roles': typeof ProtectedSettingsRolesRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/settings': typeof ProtectedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/_protected/assistant': typeof ProtectedAssistantRoute
  '/_protected/contacts': typeof ProtectedContactsRoute
  '/_protected/files': typeof ProtectedFilesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/settings/api-keys': typeof ProtectedSettingsApiKeysRoute
  '/_protected/settings/audit': typeof ProtectedSettingsAuditRoute
  '/_protected/settings/billing': typeof ProtectedSettingsBillingRoute
  '/_protected/settings/general': typeof ProtectedSettingsGeneralRoute
  '/_protected/settings/members': typeof ProtectedSettingsMembersRoute
  '/_protected/settings/roles': typeof ProtectedSettingsRolesRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/'
    | '/settings'
    | '/assistant'
    | '/contacts'
    | '/files'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/otp'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verified'
    | '/settings/api-keys'
    | '/settings/audit'
    | '/settings/billing'
    | '/settings/general'
    | '/settings/members'
    | '/settings/roles'
    | '/auth/accept-invitation/$invitationId'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/assistant'
    | '/contacts'
    | '/files'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/otp'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verified'
    | '/'
    | '/settings/api-keys'
    | '/settings/audit'
    | '/settings/billing'
    | '/settings/general'
    | '/settings/members'
    | '/settings/roles'
    | '/auth/accept-invitation/$invitationId'
    | '/settings'
  id:
    | '__root__'
    | '/auth'
    | '/_protected'
    | '/_protected/settings'
    | '/_protected/assistant'
    | '/_protected/contacts'
    | '/_protected/files'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/otp'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verified'
    | '/_protected/'
    | '/_protected/settings/api-keys'
    | '/_protected/settings/audit'
    | '/_protected/settings/billing'
    | '/_protected/settings/general'
    | '/_protected/settings/members'
    | '/_protected/settings/roles'
    | '/auth/accept-invitation/$invitationId'
    | '/_protected/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/assistant': {
      id: '/_protected/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof ProtectedAssistantRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/contacts': {
      id: '/_protected/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ProtectedContactsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/files': {
      id: '/_protected/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof ProtectedFilesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/magic-link': {
      id: '/auth/magic-link'
      path: '/magic-link'
      fullPath: '/auth/magic-link'
      preLoaderRoute: typeof AuthMagicLinkRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/verified': {
      id: '/auth/verified'
      path: '/verified'
      fullPath: '/auth/verified'
      preLoaderRoute: typeof AuthVerifiedRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/api-keys': {
      id: '/_protected/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof ProtectedSettingsApiKeysRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/audit': {
      id: '/_protected/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof ProtectedSettingsAuditRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/billing': {
      id: '/_protected/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof ProtectedSettingsBillingRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/general': {
      id: '/_protected/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof ProtectedSettingsGeneralRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/members': {
      id: '/_protected/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof ProtectedSettingsMembersRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/roles': {
      id: '/_protected/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof ProtectedSettingsRolesRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/auth/accept-invitation/$invitationId': {
      id: '/auth/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/auth/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMagicLinkRoute: typeof AuthMagicLinkRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifiedRoute: typeof AuthVerifiedRoute
  AuthAcceptInvitationInvitationIdRoute: typeof AuthAcceptInvitationInvitationIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMagicLinkRoute: AuthMagicLinkRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifiedRoute: AuthVerifiedRoute,
  AuthAcceptInvitationInvitationIdRoute: AuthAcceptInvitationInvitationIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedSettingsRouteRouteChildren {
  ProtectedSettingsApiKeysRoute: typeof ProtectedSettingsApiKeysRoute
  ProtectedSettingsAuditRoute: typeof ProtectedSettingsAuditRoute
  ProtectedSettingsBillingRoute: typeof ProtectedSettingsBillingRoute
  ProtectedSettingsGeneralRoute: typeof ProtectedSettingsGeneralRoute
  ProtectedSettingsMembersRoute: typeof ProtectedSettingsMembersRoute
  ProtectedSettingsRolesRoute: typeof ProtectedSettingsRolesRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
}

const ProtectedSettingsRouteRouteChildren: ProtectedSettingsRouteRouteChildren =
  {
    ProtectedSettingsApiKeysRoute: ProtectedSettingsApiKeysRoute,
    ProtectedSettingsAuditRoute: ProtectedSettingsAuditRoute,
    ProtectedSettingsBillingRoute: ProtectedSettingsBillingRoute,
    ProtectedSettingsGeneralRoute: ProtectedSettingsGeneralRoute,
    ProtectedSettingsMembersRoute: ProtectedSettingsMembersRoute,
    ProtectedSettingsRolesRoute: ProtectedSettingsRolesRoute,
    ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  }

const ProtectedSettingsRouteRouteWithChildren =
  ProtectedSettingsRouteRoute._addFileChildren(
    ProtectedSettingsRouteRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedSettingsRouteRoute: typeof ProtectedSettingsRouteRouteWithChildren
  ProtectedAssistantRoute: typeof ProtectedAssistantRoute
  ProtectedContactsRoute: typeof ProtectedContactsRoute
  ProtectedFilesRoute: typeof ProtectedFilesRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedSettingsRouteRoute: ProtectedSettingsRouteRouteWithChildren,
  ProtectedAssistantRoute: ProtectedAssistantRoute,
  ProtectedContactsRoute: ProtectedContactsRoute,
  ProtectedFilesRoute: ProtectedFilesRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
