import {
  disableTwoFactor,
  enableTwoFactor,
  twoFactorStateAtom,
  verifyTotp,
} from "@/atom/two-factor-atoms.js";
import type { TwoFactorFailed } from "@/atom/two-factor-atoms.js";
import { useAtomRefresh, useAtomValue } from "@effect/atom-react";
import { createFileRoute } from "@tanstack/react-router";
import { QueryError } from "@vantion/ui/app/query-error";
import { BackupCodes, TwoFactorPanel } from "@vantion/ui/settings/two-factor-panel";
import { Button } from "@vantion/ui/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@vantion/ui/ui/dialog";
import { Input } from "@vantion/ui/ui/input";
import { Label } from "@vantion/ui/ui/label";
import { Skeleton } from "@vantion/ui/ui/skeleton";
import { Cause, Effect, Option } from "effect";
import { AsyncResult } from "effect/unstable/reactivity";
import * as React from "react";
import { toast } from "sonner";

/** The QR image is generated by the browser from the URI, so nothing is uploaded. */
const qr = (uri: string) =>
  `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(uri)}`;

type Enrolment = { readonly uri: string; readonly codes: ReadonlyArray<string>; };

const Security = () => {
  const state = useAtomValue(twoFactorStateAtom);
  const refresh = useAtomRefresh(twoFactorStateAtom);

  const [password, setPassword] = React.useState("");
  const [code, setCode] = React.useState("");
  const [busy, setBusy] = React.useState(false);
  const [asking, setAsking] = React.useState<"enable" | "disable" | null>(null);
  const [enrolment, setEnrolment] = React.useState<Enrolment | null>(null);

  /**
   * The server's own words where there are any. "That password was not
   * accepted" is more use than anything this screen could invent, and every
   * failure these calls produce is a `TwoFactorFailed` carrying one.
   */
  const fail = (cause: Cause.Cause<TwoFactorFailed>, fallback: string) => {
    const error = Cause.findErrorOption(cause);

    toast.error(Option.isSome(error) ? error.value.message : fallback);
  };

  if (AsyncResult.isFailure(state)) {
    return <QueryError result={state} subject="your security settings" />;
  }

  if (!AsyncResult.isSuccess(state)) return <Skeleton className="h-64 w-full" />;

  const run = async <A,>(effect: Effect.Effect<A, TwoFactorFailed>, fallback: string) => {
    setBusy(true);
    const exit = await Effect.runPromiseExit(effect);
    setBusy(false);

    if (exit._tag === "Failure") {
      fail(exit.cause, fallback);

      return undefined;
    }

    return exit.value;
  };

  const onEnable = async () => {
    const result = await run(enableTwoFactor(password), "That password was not accepted.");

    if (result === undefined) return;

    setAsking(null);
    setPassword("");
    setEnrolment({ uri: result.totpURI, codes: result.backupCodes });
  };

  const onDisable = async () => {
    const result = await run(disableTwoFactor(password), "That password was not accepted.");
    if (result === undefined) return;

    setAsking(null);
    setPassword("");
    toast.success("Two-factor is off.");
    refresh();
  };

  /**
   * Verified before it counts. `enable` already switched it on, so a person who
   * closed this dialog without ever scanning the code would be locked out on
   * their next sign-in — confirming a code from the app is what proves they can
   * still get in.
   */
  const onVerify = async () => {
    const result = await run(verifyTotp(code), "That code was not accepted.");
    if (result === undefined) return;

    setEnrolment(null);
    setCode("");
    toast.success("Two-factor is on.");
    refresh();
  };

  return (
    <>
      <TwoFactorPanel
        enabled={state.value.enabled}
        required={state.value.required}
        busy={busy}
        onEnable={() => setAsking("enable")}
        onDisable={() => setAsking("disable")}
      />

      <Dialog open={asking !== null} onOpenChange={() => setAsking(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Confirm it is you</DialogTitle>
            <DialogDescription>
              Your password again, because a stolen session must not be able to change how this
              account signs in.
            </DialogDescription>
          </DialogHeader>

          <div className="flex flex-col gap-1.5">
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              type="password"
              autoComplete="current-password"
              value={password}
              onChange={(event) => setPassword(event.target.value)}
            />
          </div>

          <DialogFooter>
            <Button
              disabled={busy || password === ""}
              onClick={() => void (asking === "enable" ? onEnable() : onDisable())}
            >
              Continue
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={enrolment !== null} onOpenChange={() => setEnrolment(null)}>
        <DialogContent className="max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Scan this, then confirm</DialogTitle>
            <DialogDescription>
              Add it to an authenticator app, then type the code it shows.
            </DialogDescription>
          </DialogHeader>

          {enrolment === null ? null : (
            <div className="flex flex-col gap-4">
              <img
                src={qr(enrolment.uri)}
                alt="Two-factor setup code"
                className="self-center rounded-md"
                width={200}
                height={200}
              />

              <BackupCodes codes={enrolment.codes} />

              <div className="flex flex-col gap-1.5">
                <Label htmlFor="code">Code from the app</Label>
                <Input
                  id="code"
                  inputMode="numeric"
                  autoComplete="one-time-code"
                  value={code}
                  onChange={(event) => setCode(event.target.value)}
                />
              </div>
            </div>
          )}

          <DialogFooter>
            <Button disabled={busy || code === ""} onClick={() => void onVerify()}>
              Confirm
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
};

export const Route = createFileRoute("/_protected/settings/security")({
  staticData: { crumb: "Security" },
  component: Security,
});
