import * as fs from "node:fs";
import * as path from "node:path";

/**
 * The agent layer as data, read from one place.
 *
 * `.agents/skills` is where skills live and `.claude/skills` is a symlink to it. That
 * arrangement is the whole point: a skill is prose about this repository, and which agent
 * is reading it is not the skill's business. Cursor and Codex get **generated** views of
 * the same directory, so there is one source and no copy to drift.
 */

export interface Skill {
  readonly name: string;
  readonly description: string;
  /** Vendored from somebody else, or written here. */
  readonly origin: "vendored" | "first-party";
  readonly dir: string;
}

export interface LockEntry {
  readonly origin: "vendored" | "first-party";
  readonly url?: string;
  readonly version?: string;
  readonly license?: string;
  readonly licenseFile?: string;
  readonly why: string;
}

export const SKILLS_DIR = path.join(".agents", "skills");
export const AGENTS_DIR = path.join(".agents", "agents");
export const LOCK_FILE = path.join(".agents", "skills-lock.json");

interface Lock {
  readonly skills: Record<string, LockEntry>;
  readonly agents: Record<string, LockEntry>;
}

const lockFile = (repo: string): Lock =>
  JSON.parse(fs.readFileSync(path.join(repo, LOCK_FILE), "utf8")) as Lock;

export const readLock = (repo: string): Record<string, LockEntry> => lockFile(repo).skills;

export const readAgentLock = (repo: string): Record<string, LockEntry> => lockFile(repo).agents;

/**
 * The frontmatter a skill declares, read without a YAML parser.
 *
 * Only two fields matter here and both are single-line strings, so a line-wise read is
 * honest rather than lazy — and it keeps this file dependency-free, which matters because
 * `.claude/hooks/*` may end up calling it when `node_modules` is broken.
 */
const frontmatter = (source: string): Record<string, string> => {
  const match = /^---\n([\s\S]*?)\n---/.exec(source);
  if (match?.[1] === undefined) return {};

  const fields: Record<string, string> = {};

  for (const line of match[1].split("\n")) {
    const at = line.indexOf(":");
    if (at <= 0 || line.startsWith(" ")) continue;

    fields[line.slice(0, at).trim()] = line.slice(at + 1).trim().replace(/^["']|["']$/g, "");
  }

  return fields;
};

/**
 * An agent is one file, not a directory — `.agents/agents/<name>.md` — because it is a
 * prompt rather than a bundle. Claude Code reads them through the `.claude/agents`
 * symlink; Cursor and Codex have no equivalent, so their generated views list agents as
 * prose rather than pretending the concept transfers.
 */
export const readAgents = (repo: string): Array<Skill> => {
  const lock = readAgentLock(repo);
  const root = path.join(repo, AGENTS_DIR);

  if (!fs.existsSync(root)) return [];

  return fs.readdirSync(root)
    .filter((file) => file.endsWith(".md"))
    .sort()
    .map((file) => {
      const name = file.replace(/\.md$/, "");
      const fields = frontmatter(fs.readFileSync(path.join(root, file), "utf8"));

      return {
        name,
        description: fields["description"] ?? "",
        origin: lock[name]?.origin ?? "first-party",
        dir: path.posix.join(".agents", "agents", file),
      };
    });
};

export const readSkills = (repo: string): Array<Skill> => {
  const lock = readLock(repo);
  const root = path.join(repo, SKILLS_DIR);

  return fs.readdirSync(root, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
    .flatMap((name) => {
      const file = path.join(root, name, "SKILL.md");
      if (!fs.existsSync(file)) return [];

      const fields = frontmatter(fs.readFileSync(file, "utf8"));

      return [{
        name,
        description: fields["description"] ?? "",
        origin: lock[name]?.origin ?? "first-party",
        dir: path.posix.join(".agents", "skills", name),
      }];
    });
};

/**
 * Cursor reads `.cursor/rules/*.mdc`: frontmatter plus prose, one file per rule.
 *
 * These are **pointers, not copies**. A rule that inlined a skill would be a second copy
 * of prose that changes, and the failure is silent — Cursor would keep answering from the
 * stale one. `alwaysApply: false` with a description is Cursor's own "load this when it
 * looks relevant", which is the same contract a skill's description already states.
 */
export const cursorRule = (skill: Skill): string =>
  `---
description: ${skill.description}
alwaysApply: false
---

# ${skill.name}

Read \`${skill.dir}/SKILL.md\` before answering. It is the source; this file exists only so
Cursor knows the skill is there.

Generated by \`bun run agents\` from \`${SKILLS_DIR}\`. Do not edit.
`;

/**
 * Codex reads `AGENTS.md`, which this repository already has and which is written by
 * hand. What it does not do is discover a skills directory, so this is the index — one
 * line per skill, pointing at the file.
 */
export const codexSkills = (
  skills: ReadonlyArray<Skill>,
  agents: ReadonlyArray<Skill>,
): string =>
  `# Skills

Codex reads \`AGENTS.md\` at the repository root; this file is the index of the skills
beside it. Each is prose about *this* repository, and which agent reads it is not the
skill's business — \`.claude/skills\` is a symlink to the same directory and
\`.cursor/rules\` is generated from it.

Read the matching \`SKILL.md\` before working in the area it names.

${skills.map((s) => `- **${s.name}** — \`${s.dir}/SKILL.md\`\n  ${s.description}`).join("\n")}

## Agents

Claude Code runs these as subagents through \`.claude/agents\`. Codex has no equivalent, so
they are listed here as **review checklists a person can drive by hand** — each one names a
property worth checking and the order to check it in.

${agents.map((a) => `- **${a.name}** — \`${a.dir}\`\n  ${a.description}`).join("\n")}

Generated by \`bun run agents\` from \`${SKILLS_DIR}\` and \`${AGENTS_DIR}\`. Do not edit.
`;
